/* Auto-generated by utensor cli */
#ifndef __MY_MODEL_INTERFACE_H
#define __MY_MODEL_INTERFACE_H
#include "uTensor.h"

using namespace uTensor;

class MyModel : public ModelInterface<1, 1> 
{
 public:
  enum input_names : uint8_t { input_0 };
  enum output_names : uint8_t { output_0 };
  MyModel();
 protected:
  virtual void compute();
 private:
  // Operators
  TflmSymQuantOps::DepthwiseSeparableConvOperator<int8_t> op_DepthwiseSeparableConvOperator_000;

  ReferenceOperators::ReshapeOperator<int8_t> op_ReshapeOperator_001;

  TflmSymQuantOps::DequantizeOperator<float, int8_t> op_DequantizeOperator_002;

  ReferenceOperators::AddOperator<int8_t> op_AddOperator_003;

  ReferenceOperators::ReshapeOperator<int8_t> op_ReshapeOperator_004;

  ReferenceOperators::MulOperator<int8_t> op_MulOperator_005;

  ReferenceOperators::Conv2dOperator<int8_t> op_Conv2dOperator_006;

  TflmSymQuantOps::DepthwiseSeparableConvOperator<int8_t> op_DepthwiseSeparableConvOperator_007;

  TflmSymQuantOps::FullyConnectedOperator<int8_t> op_FullyConnectedOperator_008;

  ReferenceOperators::Conv2dOperator<int8_t> op_Conv2dOperator_009;

  TflmSymQuantOps::QuantizeOperator<int8_t, float> op_QuantizeOperator_010;

  ReferenceOperators::ReLUOperator<int8_t> op_ReLUOperator_011;

  // memory allocators
  localCircularArenaAllocator<10656, uint16_t> ram_allocator;
  localCircularArenaAllocator<2112, uint16_t> metadata_allocator;
};

#endif // __MY_MODEL_INTERFACE_H